obstacle_range: 3.5
raytrace_range: 4.0
# footprint: [[-0.3, -0.3], [0.3, -0.3], [0.3, 0.3], [-0.3, 0.3]] 
robot_radius: 0.4
inflation_radius: 0.45
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor 
# point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}

transform_tolerance: 0.1
robot_base_frame: base_link    # Must match your TF tree
obstacle_keep_time: 1.0